spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:mysql://mysql:3306/customer_db?allowPublicKeyRetrieval=true&useSSL=false
    username: my_user
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  doc:
    api:
      path: /customerserice/v3/api-docs
    swagger-ui:
      path: /customerservice/swagger-ui/index.html

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
