spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service.routing
            uri: lb://customerservice # load-balancing
            predicates:
              - Path=/api/**
          - id: product-service.routing
            uri: lb://productservice
            predicates:
              - Path=/api/products/**
          - id: eureka.routing
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka.static-files
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/**
          - id: user-service.routing
            uri: lb://userservice
            predicates:
              - Path=/api/auth/**
              
             # Swagger API Docs Routes
          - id: customer-service.api-docs
            uri: lb://customerservice
            predicates:
              - Path=/customerservice/v3/api-docs/**

          - id: product-service.api-docs
            uri: lb://productservice
            predicates:
              - Path=/productservice/v3/api-docs/**
            filters:
              - RewritePath=/productservice/v3/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}

          - id: user-service.api-docs
            uri: lb://userservice
            predicates:
              - Path=/userservice/v3/api-docs/**
            filters:
              - RewritePath=/userservice/v3/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}
              
            # Swagger UI Routes
          - id: customer-service.swagger-ui
            uri: lb://customerservice
            predicates:
              - Path=/customerservice/swagger-ui/**
              
          - id: product-service.swagger-ui
            uri: lb://productservice
            predicates:
              - Path=/productservice/swagger-ui/**
            filters:
              - RewritePath=/productservice/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}
              
          - id: user-service.swagger-ui
            uri: lb://userservice
            predicates:
              - Path=/userservice/swagger-ui/**
            filters:
              - RewritePath=/userservice/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}

server:
  port: 8090

eureka:
  url: http://localhost:8888
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


##load balancing algorithm
