spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service.routing
            uri: lb://customerservice # load-balancing
            predicates:
              - Path=/api/individualcustomers/**
          - id: product-service.routing
            uri: lb://productservice
            predicates:
              - Path=/api/products/**
          - id: eureka.routing
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka.static-files
            uri: ${eureka.url}
            predicates:
              - Path=/eureka/**
          - id: user-service.routing
            uri: lb://userservice
            predicates:
              - Path=/api/auth/**
            # Swagger
          - id: customer-service.swagger
            uri: lb://customerservice
            predicates:
              - Path=/api/individualcustomers/v3/api-docs
          - id: product-service.swagger
            uri: lb://productservice
            predicates:
              - Path=/api/products/v3/api-docs
          - id: user-service.swagger
            uri: lb://userservice
            predicates:
              - Path=/api/auth/v3/api-docs
          - id: customer-service.swagger-ui
            uri: lb://customerservice
            predicates:
              - Path=/api/individualcustomers/swagger-ui.html
          - id: product-service.swagger-ui
            uri: lb://productservice
            predicates:
              - Path=/api/products/swagger-ui.html
          - id: user-service.swagger-ui
            uri: lb://userservice
            predicates:
              - Path=/api/auth/swagger-ui.html

server:
  port: 8090

eureka:
  url: http://localhost:8888
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/


##load balancing algorithm
