spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://configserver:8001
    loadbalancer:
      enabled: true

eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
