spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/orderdb"
springdoc:
  api-docs:
    path: /orderservice/v3/api-docs
  swagger-ui:
    path: /orderservice/swagger-ui.html
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
