spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/user_db"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
      
springdoc:
  api-docs:
    path: /userservice/v3/api-docs
  swagger-ui:
    path: /userservice/swagger-ui.html
    
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
